// ServiceScreenStyle.js
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeContainer: { flex: 1 },
  map: { flex: 1 },
  searchBoxContainer: {
    position: 'absolute',
    top: 10,
    width: '90%',
    alignSelf: 'center',
    zIndex: 1,
    borderRadius: 8,
    padding: 5,
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  searchInputWrapper: { flex: 1, marginRight: 8 },
  searchInput: {
    height: 40,
    marginTop: 5,
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
  },
  searchListView: { backgroundColor: '#fff' },
  iconWrapper: {
    height: 40,
    width: 40,
    marginTop: 5,
    backgroundColor: '#6c757d',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#6c757d',
  },
  placeText: {
    position: 'absolute',
    bottom: 10,
    alignSelf: 'center',
    fontSize: 16,
    color: '#333',
    backgroundColor: 'rgba(255,255,255,0.8)',
    padding: 8,
    borderRadius: 8,
  },
  errorText: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    fontSize: 16,
    color: '#d14249',
    backgroundColor: 'rgba(255,255,255,0.8)',
    padding: 8,
    borderRadius: 8,
  },
  modalBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalCard: {
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 10,
    width: '90%',
    maxWidth: 400,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    alignItems: 'center',
    marginBottom: 15,
  },
  clinicName: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  detailsBox: {
    flex: 1,
    marginRight: 10,
  },
  detailText: {
    fontSize: 14,
    marginBottom: 5,
  },
  bold: { fontWeight: 'bold' },
  boldLink: {
    fontWeight: 'bold',
    color: '#70b6fa',
  },
  modalContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalText: {
    fontSize: 16,
    marginBottom: 8,
  },
  modalContainer: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    width: '80%',
    justifyContent: 'space-between',
    height: 'auto',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  leftButtons: { flexDirection: 'row' },
  acceptButton: {
    backgroundColor: '#28a745',
    padding: 10,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  declinedButton: {
    backgroundColor: '#d14249',
    padding: 10,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  viewDetailsText: {
    color: 'white',
    marginLeft: 5,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 15,
    paddingVertical: 10,
  },
  dateTimeBox: {
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
    padding: 10,
    width: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateTimeText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  dateTimeTextSmall: {
    fontSize: 10,
    fontWeight: 'normal',
  },
  distanceContainer: {
    backgroundColor: '#fff',
    padding: 8,
    borderRadius: 8,
    marginLeft: 10,
    elevation: 2,
  },
  distanceText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
});

export default styles;
