// AcceptedScreenStyle.js
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeAreaTop: { backgroundColor: '#6c757d' },
  container: { flex: 1, backgroundColor: '#ffffff' },
  topBar: {
    height: 45,
    backgroundColor: '#6c757d',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 7,
    justifyContent: 'space-between',
  },
  backButton: { padding: 10 },
  topBarTitle: { fontSize: 20, color: '#fff', fontWeight: '600' },
  searchButton: { padding: 10 },
  searchInput: {
    flex: 1,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 5,
    paddingHorizontal: 10,
    marginLeft: 10,
  },
  feed: { padding: 10 },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 100,
  },
  emptyImage: { width: 100, height: 100, marginBottom: 20 },
  emptyText: { fontSize: 18, color: '#888', textAlign: 'center' },
  header: { paddingVertical: 15, paddingHorizontal: 20 },
  post: {
    marginBottom: 15,
    backgroundColor: '#dcdcdc',
    borderRadius: 8,
    padding: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  detailsDateContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  clinicName: { fontWeight: 'bold', fontSize: 16 },
  details: { flex: 1 },
  footer: { flex: 1, marginRight: 10 },
  detailText: { fontSize: 14, marginBottom: 5 },
  bold: { fontWeight: 'bold' },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  leftButtons: { flexDirection: 'row', alignItems: 'center' },
  followUpButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#28a745',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
  },
  finishButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6c757d',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    marginRight: 5,
  },
  viewDetailsText: { color: '#fff', fontWeight: 'bold', marginLeft: 5 },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalCard: {
    backgroundColor: '#ffffff',
    borderRadius: 10,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  modalContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  closeButton: { padding: 10 },
  dateTimeBox: {
    backgroundColor: '#f0f0f0',
    borderRadius: 10,
    padding: 10,
    width: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateTimeText: { fontSize: 16, fontWeight: 'bold' },
  dateTimeTextSmall: { fontSize: 10, fontWeight: 'normal' },
});

export default styles;