// HomeScreenStyle.js
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  scrollContainer: {
    flexGrow: 1,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 15,
    marginBottom: 20,
  },
  card: {
    width: '45%',
    margin: 5,
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  cardCount: {
    fontSize: 24,
    color: '#333',
    marginTop: 10,
  },
  cardName: {
    fontSize: 18,
    color: '#333',
    marginTop: 5,
    fontWeight: 'bold',
  },
  headerText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#555',
    textTransform: 'uppercase',
  },
  subHeaderText: {
    fontSize: 14,
    color: '#555',
    marginVertical: 5,
    textAlign: 'center',
  },
  followUpSection: {
    padding: 10,
    marginTop: -10,
    shadowRadius: 5,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: '#f0f0f0',
  },
  TaskSection: {
    padding: 10,
    marginTop: 15,
    shadowRadius: 5,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: '#f0f0f0',
  },
  UpcomingSection: {
    padding: 10,
    marginTop: 15,
    shadowRadius: 5,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: '#f0f0f0',
  },
  noFollowUpsText: {
    fontSize: 16,
    color: '#888',
    textAlign: 'center',
    marginTop: 10,
  },
  followUpContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  followUpCard: {
    width: 150,
    height: 100,
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    margin: 5,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  followUpName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 5,
  },
  followUpDate: {
    fontSize: 14,
    color: '#555',
    marginTop: 2,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: '#ccc',
    marginHorizontal: 10,
  },
});

export default styles;
